# Generated by Django 4.2.5 on 2023-09-29 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Cadastro',
        ),
    ]
