# Generated by Django 4.2.5 on 2023-10-01 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_cadastro_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro',
            name='login',
        ),
    ]
